### ISSUE TITLE
Formatting by clang-format

### ISSUE THREAD

**Issue by offa** [mattgodbolt/seasocks#102]
It's probably a good idea to add a _clang-format_ config and reformat the code base with this. 
We may not get 100 % exact what we have now, but the advantages are well-known.

@mattgodbolt What do you think?

**Comment by mattgodbolt** [comment]
I'd be delighted to have a consistent look and feel. Clang format is the right tool for the job. Very happy to move to it (and to make it a unit test check maybe too?)

**Comment by offa** [comment]
Fixed by #107
