### ISSUE TITLE
Release 1.3.2 - wrong dir name in CMakeLists

### ISSUE THREAD

**Issue by rspielmann** [mattgodbolt/seasocks#121]
In order to build Release 1.3.2 (https://github.com/mattgodbolt/seasocks/tree/v1.3.2) I had to apply the patch [1] attached to this issue in order to make the build work completely.

If this hasn't been fixed in newer versions, maybe it would make sense to do so :)

[1] [001-seasocks-src-app-c-CMakeLists.txt.patch.txt](https://github.com/mattgodbolt/seasocks/files/3077606/001-seasocks-src-app-c-CMakeLists.txt.patch.txt)

**Comment by offa** [comment]
This has been fixed last year: https://github.com/mattgodbolt/seasocks/commit/a51be5dce3ff21e62318c6c11591d432dba06ac3

Please update to a more recent version, v1.4.1 includes the fix. If you have some more minutes; I'm going to create a new release in a few minutes.

**Comment by rspielmann** [comment]
Thanks @offa for the feedback, shortly after creating the issue I did in fact realize that the problem had been resolved. I picked release 1.3.2 because I'm stuck with C++11 for now, and decided to patch the broken line in CMakeLists.txt myself locally. Great library, thanks for providing it :)
