### ISSUE TITLE
Can this work with CentOS 5?

### ISSUE THREAD

**Issue by kayechica** [mattgodbolt/seasocks#122]
I currently have CentOS5/Rhel5 machine with the following old environment specs:
cmake version 2.8.11
gcc (GCC) 4.1.2
OpenSSL 0.9.8h
Will there be restrictions if I use this library in my current environment?
I had problems with libwebsockets library so I am looking for alternatives.
Please let me know.
Thanks.

**Comment by hoytech** [comment]
Probably. Why not try to compile it and then let us know?

The only thing I'm not sure about is your SSL version is quite old and I'm not sure if the API is compatible. You should really not be using this library. The 0.9.8 branch is no longer supported and your particular version has many know security bugs. Search for "0.9.8h" on this page: http://openssl.cs.utah.edu/news/vulnerabilities.html

**Comment by offa** [comment]
I don't think GCC 4.1.2 supports C++14.
