### ISSUE TITLE
This is a Linux Specific Library

### ISSUE THREAD

**Issue by yck011522** [mattgodbolt/seasocks#123]
Hi,
Thanks for creating and maintaining this library.

It would be nice if you can add the warning in the front page of the code base to warn:
"This is a Linux Specific Library, It will not compile on a  windows machine." 

I have spend 30 mins of frustration before I found the thread:
As has been concluded here: https://github.com/mattgodbolt/seasocks/issues/23
I'm cool with it. But a warning message is all it needs for a future user to avoid the same agony.

**Comment by hoytech** [comment]
On the tutorial it says:

> It'll only likely work on Linux,

but I agree this should be front and centre on the README so people don't waste time if they're not on linux (sorry about that).

BTW: I wonder if it *does* work on linux now that there is a compat layer called WSL.

**Comment by offa** [comment]
First try: #124 

> BTW: I wonder if it does work on linux now that there is a compat layer called WSL.

Or using eg. Cygwin, Mingw or Msys?

**Comment by Bokjan** [comment]
sesocks works well with WSL (tested on WSL Ubuntu).

**Comment by offa** [comment]
Should we include this info in the readme?

**Comment by Bokjan** [comment]
Not really necessary, I suppose. WSL just translates syscalls to Windows APIs, and for users, it acts like a real Linux in common scenarios.

**Comment by offa** [comment]
Readme is updated.

**Comment by offa** [comment]
I guess we can close here, feel free to reopen, if there's anything missing.
