### ISSUE TITLE
Per-message deflate causes bad_alloc on message length of 0

### ISSUE THREAD

**Issue by cake4289** [mattgodbolt/seasocks#125]
The return code of `::deflate` is not checked  - it returns Z_BUF_ERROR when:

- It has already processed data before; and
- It is passed a buffer with a length of zero

This happens when sending a message (other than the first message) over a websocket with a size of 0.

Then, resizing the output vector to `size() - 4`, which is a huge number as `size()` is zero, throws a bad_alloc exception.

I believe following RFC 7692 7.2.1 to the letter would fix this:

```
   2.  If the resulting data does not end with an empty DEFLATE block
       with no compression (the "BTYPE" bits are set to 00), append an
       empty DEFLATE block with no compression to the tail end.
```

**Comment by hoytech** [comment]
@cake4289 - Thanks for the bug report! Is it possible for you to send a pull request?

**Comment by offa** [comment]
Thanks @cake4289 for providing a fix that fast! :+1:

**Comment by hoytech** [comment]
@cake4289 - Great, thanks!
