### ISSUE TITLE
Exception and dangling connection when "Sec-WebSocket-Version" is missing

### ISSUE THREAD

**Issue by iris-ersc** [mattgodbolt/seasocks#131]
While working with seasocks and testing with `curl` I came across some (maybe) unwanted behavior: 

When there is no "Sec-WebSocket-Version" header field, seasocks throws a `invalid_argument` exception.

```
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" http://host/path
```

The header field "Sec-WebSocket-Version" is mandatory according to the WebSocket Protocol, but crashing the whole webserver because a simple `std::stoi` operates on an empty string is probably not good.

https://github.com/mattgodbolt/seasocks/blob/ec3558d66e7bed7b9d1f502c4171730668a8eb59/src/main/c/Connection.cpp#L920

**Comment by offa** [comment]
Thanks for reporting.

According the _RFC6455_ it's best to return _426 Upgrade Required_. I'll have a look at it.

**Comment by offa** [comment]
I have opened #132 to address this issue. It does handle any parsing errors now.
In case of an empty header there's a entry in the log now.

**Comment by offa** [comment]
PR merged.
