### ISSUE TITLE
-- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by karthikarumugams** [mattgodbolt/seasocks#133]
-- Configuring incomplete, errors occurred!
See also "/home/karthik/seasocks/build/CMakeFiles/CMakeOutput.log".
See also "/home/karthik/seasocks/build/CMakeFiles/CMakeError.log".

**Comment by offa** [comment]
Please provide suitable information like operation system, compiler, build logs and steps to reproduce.
