### ISSUE TITLE
Moving to Github Actions?

### ISSUE THREAD

**Issue by offa** [mattgodbolt/seasocks#147]
Since Travis has recently changed it's [pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) and has really poor performance since quite some time, we should consider moving to Github Action.

**Comment by offa** [comment]
@mattgodbolt What do you think about it? I volunteer for porting.

**Comment by mattgodbolt** [comment]
100% up for doing this! I've moved a few of my other repos to GH Actions and have been happy with the outcome. If you want to give it a go please do! Happy to help if I can.
