### ISSUE TITLE
Embedded.cpp content length may exceed compiler Limit

### ISSUE THREAD

**Issue by offa** [mattgodbolt/seasocks#16]
Please see https://travis-ci.org/offa/seasocks/jobs/86435581#L291

**Comment by mattgodbolt** [comment]
Oh my...that's unfortunate :) Will fix...

**Comment by offa** [comment]
Unfortunately it's still failing on clang: https://travis-ci.org/offa/seasocks/jobs/86673185#L291

**Comment by mattgodbolt** [comment]
Ah: my solution was not a fix after all: lots of (separate) literals concatenated are of course still one actual literal. Apols; will fix properly

**Comment by mattgodbolt** [comment]
Hopefully fixed with e2bb596818fda2dc1929d3d4019440ed7fb2ec19 - do let me know and close if you agree

**Comment by offa** [comment]
Nice, looks good now: https://travis-ci.org/offa/seasocks/builds/86826764

Pull request follows.

**Comment by offa** [comment]
Ready: #19
