### ISSUE TITLE
You're all nothing but useless shills, Matt

### ISSUE THREAD

**Issue by ghost** [mattgodbolt/seasocks#186]
@mattgodbolt  Death to you Matt, you cheap loser slave. Death to you for openly promoting the BBC's disgusting & garbage & childish TV series, which starts with a disgusting 6 letter clownish word and is followed by "Who". Death to you and death to the BBC and every moron who made or supported that disgusting TV series. 

Death to every loser donkey who uses that disgusting & racist 6 letter donkey word. Death to you for openly promoting donkeys who work for the garbage  & useless so called "health" "sector". Death to you for being such stupid mainstream shills and praising those daft morons. Death to you for promoting those stupid childish ego pigs, who work for such a garbage "sector". You're all nothing but useless shills. Your projects are nothing but utter trash, and You have no potential, and are a complete and utter laughable failure, Matt. Death to "universities" [DUMPSTERversities] Death to every idiot who uses the stupid 6-letter "prefixes" when mentioning first names. Death to you all. Have a sad life and painful death, Matt.
Death to the UK and death to its garbage and useless so called "national" [evil] "service". Don't stay at home, and don't protect the UK's garbage & donkey so called "national" [clown] "service".
And one other thing.
None of you clowns are engineers, and you'll never be close. There is no such thing as "software" "engineering". That is the stupidest and most pathetic lie ever.

 Shame on you for mentioning the word "engineering" when making that stupid video about DOOM. To hell with monkey losers like john carmack & john romero and their garbage games. Stop being disrespectful to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with scriptkiddos like  you monkeys sitting behind a keyboard and writing code. Software/game dev is easy and for kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Quit making false claims against engineering. And stop being disrespectful to real Engineers (Mechanical Engineering is the ONLY Engineering). 
Hope your dirty and cheap throats get slit, silly Matt.
@ShameOnMattBadbolt

**Comment by mattgodbolt** [comment]
thanks @madebr

**Comment by madebr** [comment]
No problem ❤️.
I'm bracing myself for AI powered hate speech.
