### ISSUE TITLE
Multipart responses

### ISSUE THREAD

**Issue by AustinSchuh** [mattgodbolt/seasocks#21]
I've been enjoying using seasocks for websocket content.

I want to stream mjpegs from seasocks.  To do this, I need to send a multipart http response.  Seasocks looks like it really wants you to generate the entire page response and then it will send that all at once.  Is there a way to send a multipart response (where the response comes back in chunks spread out over time)?  I don't see it from the interface provided for the response.

**Comment by mattgodbolt** [comment]
There isn't currently a way to stream output. It's something that would definitely be nice; and I would welcome patches to add it. It's not on my immediate list of things to do, but I may be able to take a look. Does require a fair change to the way things are done though :)

**Comment by AustinSchuh** [comment]
Have you thought about what that interface would look like?  If/when I get time, I wouldn't mind taking a look, but I don't want to go in a direction that isn't what you are kind of thinking.

(Completely unrelated, I've got some fixes to make seasocks work on ARM that I need to make time to send you a pull request for...)

**Comment by mattgodbolt** [comment]
I haven't, other than musing on the walk home this evening...suggestions
very welcome as Seasocks is very synchronous (on purpose, mostly).

Will be glad of the ARM patches too!

On Wed, Nov 11, 2015 at 9:27 PM, Austin Schuh <notifications@github.com>
wrote:

> Have you thought about what that interface would look like? If/when I get
> time, I wouldn't mind taking a look, but I don't want to go in a direction
> that isn't what you are kind of thinking.
>
> (Completely unrelated, I've got some fixes to make seasocks work on ARM
> that I need to make time to send you a pull request for...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/seasocks/issues/21#issuecomment-155986267>
> .
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Am about to merge in an asynch branch which is the first step to multi-part replies.

**Comment by mattgodbolt** [comment]
If streaming is what you need, 40a89b77b0f3f08ea8fa6a05826ba6803f9053b8 adds support for chunked, asynchronous responses. I don't know how HTTP multipart fits into this (I can't see how it would help), but if you want to stream data back you can now do so.

See https://github.com/mattgodbolt/seasocks/blob/master/src/app/c/async_test.cpp for details on how you might achieve this.

**Comment by dgu123** [comment]
thanks Matt

**Comment by mattgodbolt** [comment]
@AustinSchuh were you ever able to take a look? Now Seasocks has async replies it might be possible to do what you want it to do, or at least it might be easier to add the support you need?

**Comment by caffinatedmonkey** [comment]
Ref #70

**Comment by chaiken** [comment]
@mattgodbolt I work with @AustinSchuh  and am happy to report that now, at last, we have updated our in-house version of seasocks to include this patch, and are using it multiple different ways in our applications, both for websockets and static pages.  Sorry for taking so long to get back to you, and thanks also for Compiler-Explorer!

**Comment by mattgodbolt** [comment]
Thanks @chaiken for your kind words, and for confirming this works! I'm going to close this now but feel free to comment if you feel there's more we could do to make this better.
