### ISSUE TITLE
Compiling seasocks on MinGW

### ISSUE THREAD

**Issue by tomaszwota** [mattgodbolt/seasocks#23]
I get an error about missing arpa/inet.h - do you not use winsock2.h on Windows? Or is seasocks not made portable to Windows?

**Comment by mattgodbolt** [comment]
Seasocks is sadly very Linux (and MacOS) specific. I'd be happy to accept patches to get it working on Windows but it doesn't compile for it right now.

**Comment by tomaszwota** [comment]
Ah, okay, thanks for responding.

**Comment by mattgodbolt** [comment]
Closing; we're very linux-specific still. Happy to accept patches if people fancy porting it though.
