### ISSUE TITLE
Error During compilation

### ISSUE THREAD

**Issue by dgu123** [mattgodbolt/seasocks#25]
Hello
the compilcation fail for me ( **all warnings being treated as errors**) on the latest update :
 11%] Building CXX object src/main/c/CMakeFiles/seasocks.dir/**Connection**.cpp.o
Connection.cpp:
 In member function ‘void seasocks::Connection::writeChunkHeader(size_t)’:

Connection.cpp:934:65: erreur: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
                         _chunk ? "\r\n%lx\r\n" : "%lx\r\n", size);

regards,
david

**Comment by mattgodbolt** [comment]
Thanks for the report. Will get fixed. As I wrote it I bet myself I'd have issues like this! :)
