### ISSUE TITLE
Response getting corrupt - question

### ISSUE THREAD

**Issue by skn2020** [mattgodbolt/seasocks#28]
I have written the following code (reduced and modified to the essential parts for posting here) to implement a response to a uri path "show". I want to generate a response in the code and return it. I generated this response in many different ways, but the result is always the following error.

When I return a response string of length >=1000, the client either does not receive the payload or receives the first few characters. For all response strings of length < 1000, it has worked well. I tried to hard code the string, read it from a file, generate it programmatically etc. I tried to return as "text/plain", "application/json","text/html", but no help. It is possible that the magic number 1000 may be just a random coincidence, but it was consistent in over 30 tests I did. When I tried to do the same long responses (>1000) by modifying the example code given in "ph_test.cpp", and it has no such problem. What am I doing wrong?

```
struct DataHandler : CrackedUriPageHandler {    
    DataHandler(){}; //my code has one argument for the constructor, which is irrelevant here
    virtual std::shared_ptr<Response> handle(const CrackedUri &uri,
                                             const Request &request) override {
        std::string resp = "";
        for(int i=0; i< 999; i++) { // <= 999 is OK, but >=1000 is giving the error  
            resp += "m";
        }
        return Response::textResponse(resp);        
    };
};

//server starting code
auto root = make_shared<RootPageHandler>();
auto pathHandler = make_shared<PathHandler>("show", make_shared<DataHandler>());        
root->add(pathHandler);  
server.addPageHandler(root);
server.serve(server_root.data(), server_port); //server_root and server port come from elsewhere
```

The response is like (where the length 1020 is correct, but the content is missing after one char):

```
200 OK
Server:  Seasocks/unversioned
Date:  Tue, 19 Apr 2016 01:58:52 GMT
Access-Control-Allow-Origin:  *
Content-Length:  1,020
Content-Type:  text/plain
Connection:  keep-alive
Last-Modified:  Tue, 19 Apr 2016 01:58:52 GMT
Pragma:  no-cache
Cache-Control:  no-store
Expires:  Tue, 19 Apr 2016 01:58:52 GMT

m
```

Compiler info: gcc 4.8.5 20150623 (Red Hat 4.8.5-4)
CMake options: ADD_DEFINITIONS(-Wall -Wextra -pedantic -ggdb3 -fPIC)

**Comment by mattgodbolt** [comment]
Wow; seems like you're doing everything right there. Will investigate: thanks for the report.

**Comment by mattgodbolt** [comment]
if it's not sensitive, can you try running `strace -o /tmp/trace.log -f <<your program and args>>` and see if you can get it to happen? I'd love to see if we can catch it doing something unusual. Also, if possible running gdb and putting a breakpoint at `Connection::payload` . It really ought to get to the `write(data, size, flush)` call with params of `data` = pointer to your "mmmmm..." string, `size` = 1000, and `flush` true.

I'll keep digging around on my side.

**Comment by mattgodbolt** [comment]
Drawing a blank here. Best thing I can think of is some hitherto undiscovered bug in Seasocks's buffering. If the OS buffers are only ~1KB, then at the point Seasocks gets a non-full send (at `Connection::write` line 325ish) it needs to buffer. Maybe there's an issue there.

What OS and architecture are you on? Sorry for the vague rambles here, I'm drawing blanks still on my side (just tried a 10MB 'm' document on my side, no joy)

**Comment by mattgodbolt** [comment]
Hmm - I just noticed your `Content-Length` has a comma in it:

```
Content-Length:  1,020
```

Could your program be setting some global locale thing that's somehow affecting how my `toString` is executing? There should be no commas in the value here...my guess is the curl/whatever is interpreting the length as "1" instead of 1020 once there's 4 digits...

**Comment by skn2020** [comment]
Yes, Matt. It was the content length. Thanks for the quick action on your part. 
The problem was that my code had  `locale::global(locale("en_US.utf8"));` in it. That caused the comma. I changed it to  `locale::global(locale("C"));` and the problem went away. Thanks a lot. I like seasocks. I am trying to replace my libhttpserver with seasocks for 1. static content 2. programmatic content response 3. websockets. So far I like it a lot.

**Comment by mattgodbolt** [comment]
Thanks for confirming and for the compliments! I'll try and fix the
underlying issue any way: seasocks should not force you to pick a
particular locale!

**Comment by skn2020** [comment]
Where do I fix your code to bring back the en_US.utf8 locale and fix the comma problem? It must be where the content length is made into a string.

**Comment by mattgodbolt** [comment]
The code is currently in toString but I'm not sure what the "right" fix is.
Probably to abandon toString and generate the right values in ascii
directly to avoid locale complications!

**Comment by skn2020** [comment]
May be you can imbue  a "C"  locale (temporarily) into a stringstream object before injecting the content length into it using `<<`. Then call its str() method to get string. you may need to save the original locale using ios_base::getloc.

**Comment by skn2020** [comment]
I don't think you even need to save the original locale. I have the following working code elsewhere in my program.
```
int r = std::rand();
stringstream ss;
ss.imbue(locale("C")); 
ss << "" << std::hex << r;
string s = ss.str();
```

**Comment by mattgodbolt** [comment]
That sounds about right. I'll implement that fix (unless you'd like to do a
pull request?)

**Comment by skn2020** [comment]
You may please go ahead and implement the fix. Thank you.

**Comment by mattgodbolt** [comment]
Just implementing the fix and trying a test here. Trying to repro the original problem: On my computer, setting `std::locale::global(std::locale("en_US.utf8"));` does not cause the commas to appear. Can you think of any other settings you might have that would cause the commas to appear? I'm not good with locales, maybe there's an LC_* environment variable I need too?

I'd like to be certain I'm actually fixing the issue :)

**Comment by mattgodbolt** [comment]
It seems harmless enough: have checked in the fix anyway.

**Comment by skn2020** [comment]
I tested again with `str.imbue(std::locale("en_US.utf8"))` inside toString(..) and it makes the comma. When I put `str.imbue(std::locale("C"))`, comma does not appear. I tested another locale `zh_CN.utf8` which also makes the comma appear. Without the fix, the global locale of `en_US.utf8` and `zh_CN.utf8` both cause comma. 

I am on CentOS 7, set to US region and English language. Not sure why the behavior is different from yours. Typing in the `locale` command in my shell shows:

```
# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by mattgodbolt** [comment]
I accidentally left the fix commented out! And still all the tests passed :(

**Comment by mattgodbolt** [comment]
That's really weird. It still passes on both travis (https://travis-ci.org/mattgodbolt/seasocks/builds/124176299) and on my two computers. My laptop is en_GB.UTF-8 across the board, and my work machine is:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I'm testing with the global setting (see https://github.com/mattgodbolt/seasocks/blob/master/src/test/c/ToStringTests.cpp#L34 ) - any ideas what my test may be doing wrong to not show up the issue.

I'll check in the fix again (this time with it commented in) but will leave this bug open for now.

**Comment by skn2020** [comment]
In your test, are you inadvertently passing a string argument to toString(), instead of a number?

**Comment by mattgodbolt** [comment]
Oh good grief...yes I am! Thanks for spotting my mistake! Will retest and
hopefully I can close this :)

**Comment by mattgodbolt** [comment]
Yes! That was it! Hahah -- thanks again :)
