### ISSUE TITLE
URL containing two slashes together not working

### ISSUE THREAD

**Issue by skn2020** [mattgodbolt/seasocks#29]
If a URL contains two slashes together, like `http://localhost:8080/a//b/c` or `http://localhost:8080//a/b/c`, it is not treated the same way as the one slashed version `http://localhost:8080/a/b/c`. 

Is this the expected behavior?

**Comment by skn2020** [comment]
May be I reported this prematurely. Seems to work OK for file system based URL serving static files. But for the programmatic handling of URI is up to me. In there, I am getting `CrackedUri`'s path() vector to have empty strings, which is caused by the multiple slashes in the URL. So it is to be parsed carefully looking for empty strings. So this may be the expected behavior, right?

**Comment by mattgodbolt** [comment]
I *think* Seasocks is doing the Right Thing™:
https://url.spec.whatwg.org/#syntax-url-path-relative indicates that the
"path" is a series of path parts separated by slashes. That means "
foo.org///" *is* a different URL from "foo.org/".  If one chooses to
interpret an empty path part as a "same directory" like the file handler
effectively does, then I guess that's OK but the URLs are different.

I'm no expert on this though!

**Comment by mattgodbolt** [comment]
Closing here: I think it's doing it right, however weird it is...
