### ISSUE TITLE
The example code doesn't work in chrome

### ISSUE THREAD

**Issue by henrywoo** [mattgodbolt/seasocks#3]
"See src/app/c/ws_test.cpp for an example"

The example code doesn't work in Chrome(43.0.2357.132 m), but works in IE11 and Firefox 39.0.

The digital number doesn't change at all in Chrome no matter how you click it.

Is there any special issue for Chrome? Or something wrong in the app.js?

**Comment by mattgodbolt** [comment]
I developed the test exclusively on Chrome on Linux, so I'm surprised :)

What version of Chrome are you using?

Thanks, Matt

On Tue, Jul 21, 2015 at 1:03 AM, Fuheng Wu <notifications@github.com> wrote:

> "See src/app/c/ws_test.cpp for an example"
>
> The example code doesn't work in Chrome, but works in IE11 and Firefox
> 39.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/seasocks/issues/3>.
>



-- 
Matt

**Comment by henrywoo** [comment]
Really? That is strange. My Chrome version: 43.0.2357.132 m.

**Comment by mattgodbolt** [comment]
Can you describe more about what happens? Is there any output in the
JavaScript console?

Thanks!

**Comment by henrywoo** [comment]
Now I have updated my chrome and it works fine.

**Comment by mattgodbolt** [comment]
Thanks: I wonder what was happening!
