### ISSUE TITLE
How does this compare to Beast?

### ISSUE THREAD

**Issue by vinniefalco** [mattgodbolt/seasocks#33]
How does this compare to Beast, which offers WebSocket and HTTP implementations?
http://vinniefalco.github.io/

**Comment by offa** [comment]
It has no dependencies.

**Comment by vinniefalco** [comment]
Its platform specific?

**Comment by mattgodbolt** [comment]
Yup it's BSD sockets specific. I believe it works on both OSX and Linux. No external dependencies as had been said above.
