### ISSUE TITLE
Multi-thread request

### ISSUE THREAD

**Issue by Cyrus414** [mattgodbolt/seasocks#34]
I run the ws_test example and use java as the client, when I use multi thread to request the response comes one by one, it looks like the server can not handle multi thread request at the same time.

**Comment by mattgodbolt** [comment]
That's right: Seasocks is single threaded by design. It's possible to have asynchronous responses (e.g. see [this example](https://github.com/mattgodbolt/seasocks/blob/master/src/app/c/async_test.cpp)), but the server will only reply to one request at a time.
