### ISSUE TITLE
can i install it from any apt source?

### ISSUE THREAD

**Issue by henrywoo** [mattgodbolt/seasocks#4]
Thanks Matt for this project. I am now using it in my project: http://www.quant365.com/post/57/

I wonder if I can install it from any apt source? that will be much simpler than download and compile.

**Comment by mattgodbolt** [comment]
Here's no apt source. Seasocks is more of a useful library to integrate into your own application than a standalone app in its own right. You'd be welcome to publish it somewhere but I have no plans to do so myself.

**Comment by mattgodbolt** [comment]
And great to hear you've been able to use it! :(

**Comment by mattgodbolt** [comment]
:) I mean! Typo; am out and using a phone to type!

**Comment by henrywoo** [comment]
Got it. Thanks Matt.
