### ISSUE TITLE
Received hybi frame with unknown opcode 10

### ISSUE THREAD

**Issue by naylor1043** [mattgodbolt/seasocks#40]
Firstly, seasocks is great! Loving the easy c++ connectivity.

Running seasocks on a Pi, using Win10 based clients. Chrome is fine, but both IE and Edge cause "Received hybi frame with unknown opcode 10", followed by a disconnect.

Assume 99% this is a ME issue, so any ideas where I should start looking?

Cheers.

Bruce.

**Comment by mattgodbolt** [comment]
Hi there,

Thanks for the kind words about seasocks. I'd doubt it's your fault here;
my guess is there's a flaw in the seasocks handling of websockets! I've
only ever used it with Chrome and Firefox. I don't have easy access to a
Windows machine for edge but I'll see what I can do!

Do you happen to have wireshark or similar installed? A really handy thing
to have would be a capture of the network traffic to and from seasocks. No
worries if not!

Thanks, Matt

**Comment by naylor1043** [comment]
Hi Matt,

Thanks for the prompt response. Sorry, no WireShark I'm afraid. Takes IE/Edge 20-30 seconds before the error occurs after initial connection. All seems fine upto the error/disconnect.

Sorry, another more pressing question: my app is talking to hardware via USB on one thread, and Seasocks is in another thread where I'm calling Server->poll(0) + other housekeeping. How can I "WebSocket::send" data from the seasocks server thread or other thread? Looked at your example code in GitHub, but couldn't get my head around it - I'm just a dumb Windows MFC guy, never got into Std :(

Thanks once again.

Bruce.

**Comment by mattgodbolt** [comment]
Hi Bruce. First up, I've been unable to find a Windows machine that's up to date enough to run Edge or a recent enough IE, but I'll keep looking.

As for the send, you have two alternatives:

- keep a list of things that need to be sent yourself and send them just before after the `server->poll()` on the thread. (What other housekeeping do you need btw? The `poll` method is usually useful if you want to avoid multiple threads, and do the multiplexing yourself)
- the "normal" way is to give Seasocks a `Runnable` or lambda. Call `Server->execute([]{ socket->send(); })` or similar. This schedules the thing you pass to it to be run on the thread executing Seasocks. You'll have to be careful about lifetimes of the `socket` though. 

The documentation is poor: I apologise. If you need more help please don't hesitate to contact me directly (matt@godbolt.org) and we can save polluting this bug with offtopic stuff!

Cheers, Matt

**Comment by mattgodbolt** [comment]
And..back to the bug: "10" is hybi PONG which I am surprised to see Edge send...should be straightforward to fix though!

**Comment by mattgodbolt** [comment]
A Pong frame MAY be sent unsolicited.  This serves as a
    unidirectional heartbeat.  A response to an unsolicited pong is not
    expected.

**Comment by mattgodbolt** [comment]
I've checked what I believe is a fix for this bug: can you test when you have a mo and let me know? Thanks!
