### ISSUE TITLE
Occasional test failures at Travis CI

### ISSUE THREAD

**Issue by offa** [mattgodbolt/seasocks#44]
Occasionally there are test failures on travis ci builds. Random builds fail at the `ctest -D ExperimentalMemCheck` step – with compiler varying from build to build.

After one or two re-runs, the build is ok. No failure locally.

### Output on failure:

```
$ ctest -D ExperimentalMemCheck
   Site: testing-gce-8767ab6f-b1a6-4f55-81d6-fa8f865a2e58
   Build name: Linux-g++-4.7
Memory check project /home/travis/build/offa/seasocks/build
    Start 1: AllTests
1/1 MemCheck #1: AllTests .........................***Failed   21.70 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  21.70 sec

The following tests FAILED:
	  1 - AllTests (Failed)
-- Processing memory checking output: 
Memory checking results:
Errors while running CTest
```

### Examples

- https://travis-ci.org/offa/seasocks/jobs/178529492
- https://travis-ci.org/offa/seasocks/jobs/188547286
- https://travis-ci.org/offa/seasocks/jobs/188547297

**Comment by offa** [comment]
As there are no failures at the mainline so far, maybe it's just an issue on my fork? Even though it's exact the same content; even *master* had failures.

**Comment by mattgodbolt** [comment]
Super weird. I'll take a look; will run under valgrind and the address
sanitiser

**Comment by mattgodbolt** [comment]
Running locally yields the logfile of:

```
==13905== 72,704 bytes in 1 blocks are still reachable in loss record 1 of 1
==13905==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13905==    by 0x50E0EFF: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==13905==    by 0x40104E9: call_init.part.0 (dl-init.c:72)
==13905==    by 0x40105FA: call_init (dl-init.c:30)
==13905==    by 0x40105FA: _dl_init (dl-init.c:120)
==13905==    by 0x4000CF9: ??? (in /lib/x86_64-linux-gnu/ld-2.23.so)
==13905== 
```
So I suspect there's something missing from the valgrind suppressions file for the compilers. I'll check in an appropriate file.

**Comment by mattgodbolt** [comment]
I found a specific entry for the leak: https://gcc.gnu.org/ml/gcc-bugs/2015-12/msg00796.html

**Comment by offa** [comment]
I have a suppression file for this: https://github.com/offa/stm32-eth/blob/master/script/memcheck.suppression

**Comment by mattgodbolt** [comment]
Yes, it is strange: why it happens only on yours and not my builds and so on...perhaps it's the version of valgrind available on the nodes it builds on...

Anyway, I'll use your suppression file once I've found out how to get CMake to pass it to valgrind. Thanks!

**Comment by mattgodbolt** [comment]
Four hours later...I think I have worked it how to do it...

**Comment by offa** [comment]
Thank you @mattgodbolt !
