### ISSUE TITLE
Run code periodically on seasocks thread

### ISSUE THREAD

**Issue by hoytech** [mattgodbolt/seasocks#47]
Hi! I was wondering if there is an easy/"best" way to periodically run some code on the seasocks thread. What I want to do is check if there are no current connections and if there haven't been any for the last 10 minutes or so then shutdown the server (It will get started again on demand when needed).

I can think of a couple ways now:

* Create another epoll() descriptor and embed seasocks's epoll() inside it as done in the `ws_test_poll.cpp` test (a bit annoying to code on the application side, but not intolerable)
* Create another thread that's basically `while(1) { sleep(60); server->execute(...); }` (requires starting another thread in each seasocks process)

I just wanted to check if there was any easy way to hook into seasocks' epoll_wait() loop as it stands and, if not, if this would be something you'd consider adding to the API.

Thanks!

**Comment by mattgodbolt** [comment]
Hi!

Without making changes to Seasocks, those are probably the best two ways to achieve your goals.  We use something akin to the second approach in our use of Seasocks at work, where most of the action is driven elsewhere (and has its own periodic job scheduler that can then `server->execute()`).

I'd happily accept a patch to put periodic work into Seasocks itself if you have better ideas though.

**Comment by hoytech** [comment]
For now I've just gone with the thread approach. When I get some time I'll try to figure out what I'd like the API to look like and then send a patch. Thanks again!
