### ISSUE TITLE
Support compression

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/seasocks#5]
Might be nice to support: http://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-28

**Comment by offa** [comment]
Isn't this fixed by #60 now?

**Comment by hoytech** [comment]
The basic compression is working for me, but there is potentially some work to do before we can definitively say we support compression. See the commit message in #60 for details. Although perhaps those items ought to be broken down into separate issues?

**Comment by mattgodbolt** [comment]
I'm happy enough to say this is done, and if anyone cares about the things in #60 we can open new issues; but right now it seems "good enough" - thanks again!
