### ISSUE TITLE
Some code related questions

### ISSUE THREAD

**Issue by offa** [mattgodbolt/seasocks#57]
I have some code related questions:

1. Is the `-ggdb3` flag still necessary? It's enabled for all build types; but mainly debug related (correct?).
1. Are the compiler checks for `map::emplace()` and `override` still necessary? Any C++11 conform compiler should support these<sup>i)</sup>.

-----------------------
<sup>i)</sup> The test for `<atomic>` isn't affected by this, as it still serves a valid reason – eg. some embedded systems may not support it.

**Comment by mattgodbolt** [comment]
1. I think so. It's enabled for all build types on purpose: should Seasocks ever crash, then I see no drawback to having debug symbols. I appreciate this is really a "RelWithDebInfo" type build all the time, so I could be swayed to building Seasocks for my own uses as "RelWithDebInfo".
2. Probably not required any more. I think we're pretty much reliant on C++11 features now, so I'd have no problem removing them, and seeing who (if anyone!) complains!

**Comment by mattgodbolt** [comment]
I'm not aware of any embedded system that doesn't provide atomics - do you have any links to those that do? My understanding is that in the worst case, atomics will drop back to a big global lock on such platforms.

**Comment by offa** [comment]
> I think so. It's enabled for all build types on purpose: should Seasocks ever crash, then I see no drawback to having debug symbols. I appreciate this is really a "RelWithDebInfo" type build all the time, so I could be swayed to building Seasocks for my own uses as "RelWithDebInfo".

I see, makes sense. Is there a difference between `-ggdb3` and the flags added by *RelWithDepInfo*? If so, we can add an option to enable that – or add it to the build types default flags.

> Probably not required any more. I think we're pretty much reliant on C++11 features now, so I'd have no problem removing them, and seeing who (if anyone!) complains!

If there's something missing, Travis should complain anyway.

> I'm not aware of any embedded system that doesn't provide atomics - do you have any links to those that do? My understanding is that in the worst case, atomics will drop back to a big global lock on such platforms.

Sorry, I was completely on the wrong track here … I had some small embedded systems in mind – but these do not have an OS or Socket anyway …

**Comment by offa** [comment]
At least Gcc 4.7 + and Clang 3.6+ work without the checks.

**Comment by mattgodbolt** [comment]
re: flags and ggdb3: I don't know what RelWithDebInfo does, I'll be honest. I'm a Makefile guy and so CMake stuff is still pretty new. I'd not be against removing it to be honest now I've thought about it: I can adjust flags for my purposes locally.

**Comment by offa** [comment]
The CMake documentation does not say much detailed about it:

> compiler flags for compiling a release build with debug flags from C++ sources. 

https://cmake.org/Wiki/CMake_Useful_Variables

**Comment by offa** [comment]
I've compared the flags between Release and RelWithDebInfo:

- Release: -O3
- RelWithDebInfo: -O2 -g

Both define NDEBUG.

**Comment by mattgodbolt** [comment]
Let's just drop the -ggdb3 then. Thanjs for checking!

**Comment by offa** [comment]
Ok, I'll open a PR.

**Comment by offa** [comment]
All questions are answered, thanks @mattgodbolt 👍
