### ISSUE TITLE
findEmbeddedContent symbol missing

### ISSUE THREAD

**Issue by hoytech** [mattgodbolt/seasocks#62]
After installing the latest version of seasocks, I'm having trouble building against `libseasocks.a`:

```
/usr/local/lib/libseasocks.a(Connection.cpp.o): In function `seasocks::Connection::sendError(seasocks::ResponseCode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Connection.cpp:(.text+0x4c2c): undefined reference to `findEmbeddedContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib/libseasocks.a(Connection.cpp.o): In function `seasocks::Connection::send404()':
Connection.cpp:(.text+0x52b5): undefined reference to `findEmbeddedContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/lib/libseasocks.a(Connection.cpp.o): In function `seasocks::Connection::processHeaders(unsigned char*, unsigned char*)':
Connection.cpp:(.text+0x6424): undefined reference to `findEmbeddedContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```

**Comment by offa** [comment]
Go to  look for a `Config.h` in `src/main/c/internal/` – if there's one, remove it.

**Comment by hoytech** [comment]
No, there isn't one. It looks like the symbol is in ./src/main/web/libembedded.a but this file is not installed by "make install"

**Comment by offa** [comment]
Can you build the embedded content (`make embedded`)?

**Comment by hoytech** [comment]
Yes, that works fine. However it creates the file `./src/main/web/libembedded.a` which isn't installed with `make install`

**Comment by offa** [comment]
The libembedded is finally included into the seasocks library.

**Comment by hoytech** [comment]
You mean into libseasocks.so right? Yes I can link against that OK. If statically compiling seasocks into your app is not supported, maybe `libseasocks.a` should not be installed?

```
$ sudo make install
...
-- Installing: /usr/local/lib/libseasocks.a
-- Installing: /usr/local/lib/libseasocks.so
```

If `libseasocks.a` is deprecated that's fine, I'll just point out that this was working fine for me as of version 1.2.5.

**Comment by offa** [comment]
No, you can use both (static and dynamic). 

What's a bit curios to me: Do the tests compile on your system? The tests link seasocks (static) and even use the `findEmbeddedContent()` function.

**Comment by hoytech** [comment]
Cool ya static is slightly easier for me at the moment.

Yes, `make test` succeeds:

```
doug@comet:~/tp/seasocks/build$ make test
Running tests...
Test project /home/doug/tp/seasocks/build
    Start 1: AllTests
1/1 Test #1: AllTests .........................   Passed    0.35 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.35 sec
```

If the `nm` output helps at all:

```
doug@comet:~/tp/seasocks/build$ nm -a ./src/main/web/libembedded.a|grep -i findEmbe
0000000000000000 T _Z19findEmbeddedContentRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
doug@comet:~/tp/seasocks/build$ nm -a ./src/main/c/libseasocks.a|grep -i findemb
                 U _Z19findEmbeddedContentRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by offa** [comment]
I'm able to reproduce it; I'll have a look on it.

**Comment by offa** [comment]
@hoytech can you checkout my `issue62-static_lib` branch and test again?

**Comment by hoytech** [comment]
Yes, this seems to fix it. Thanks!

**Comment by offa** [comment]
Thanks for testing, I'll open a PR for it.
