### ISSUE TITLE
Make ZLIB/deflate support optional

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/seasocks#72]
Some users don't need deflate and might want to remove a library dependence. Making the zlib optional seems somewhat straightforward.

**Comment by offa** [comment]
This can be solved by the build system I guess.

**Comment by offa** [comment]
The code may need some refactoring to separate the compression parts and make possible to disable them.

**Comment by mattgodbolt** [comment]
Right - I'm pretty much done with a change for this; it was pretty
straightforward.

**Comment by offa** [comment]
Should we pack this into a new release (v1.3.1)?

**Comment by mattgodbolt** [comment]
I guess we should!

**Comment by offa** [comment]
Version is updated.

**Comment by mattgodbolt** [comment]
Thanks!

**Comment by offa** [comment]
@mattgodbolt  Are you creating tag & release?

**Comment by mattgodbolt** [comment]
I can do - I misread the notification and thought you'd done so already :)

**Comment by mattgodbolt** [comment]
Forgot to post but I made a release last night! thanks all!
