### ISSUE TITLE
conan.io package

### ISSUE THREAD

**Issue by eyck** [mattgodbolt/seasocks#80]
Hi,

to simplify the reuse of the library in other projects I created a conan.io package recipe and uploaded the resulting package to a public bintray repo at: https://bintray.com/minres/conan-repo (conan remote url is https://dl.bintray.com/minres/conan-repo/)

I don't know if it makes sense to add the package recipe to this repo. But in case it can be found at https://github.com/Minres/conan-recipes/tree/master/Seasocks

**Comment by mattgodbolt** [comment]
Thanks so much for this. I'm only just starting to learn about Conan. I'll have a think! Cheers!

**Comment by offa** [comment]
I have used Conan for some projects recently and supporting it would be a great enhancement and simplification for client projects. Even more if we can get it into [conan-center](https://bintray.com/conan/conan-center).

@eyck I'm not sure either what's the better choice, and I don't see any recommended best practice. However, there are many libraries around (eg. Catch2) which ship the recipe in the repository.

**Comment by eyck** [comment]
Well, this depends of the maintainer itself and his/her affinity to support conan.io. The nice thing is that there is no need to ship it with the library which allows to keep it separate.

**Comment by offa** [comment]
From what I've found in the [conan docs](https://docs.conan.io/en/latest/creating_packages/package_repo.html):

> ### Recipe and Sources in a Different Repo
> 
> In the previous section, we fetched the sources of our library from an external repository. It is a typical workflow for packaging third party libraries.
> […]
> ### Recipe and Sources in the Same Repo
> 
> Sometimes it is more convenient to have the recipe and source code together in the same repository. This is true especially if you are developing and packaging your own library, and not one from a third-party.

So shipping it with the repo seems better suited to me (though, I'm very new to conan …).

@mattgodbolt any preferences?

**Comment by offa** [comment]
One advantage of keeping the recipe in the repository is, that we can use it for development too. Dependencies are available through conan and it's no longer necessary to manually update eg. the catch headers.

**Comment by offa** [comment]
There's another suitable approach now: We could ship it via [conan-center](https://github.com/conan-io/conan-center-index).

**Comment by jgsogo** [comment]
Already available in Conan Center 🎉  https://github.com/conan-io/conan-center-index/pull/2452

```
⇒  conan search -r conan-center seasocks
Existing package recipes:

seasocks/1.4.4
```

Thanks!
