### ISSUE TITLE
Get query string parameters

### ISSUE THREAD

**Issue by asmyasnikov** [mattgodbolt/seasocks#84]
Hi!
How to get query string parameters in GET/POST request handler?

**Comment by 0xcaff** [comment]
I believe you can use [CrackedUri](https://github.com/mattgodbolt/seasocks/blob/524a98409ba45d6b1ba71069ebe3c7b5d30db0a5/src/main/c/seasocks/util/CrackedUri.h) and [CrackedUriHandler](https://github.com/mattgodbolt/seasocks/blob/c56265c610807d3790715cd76697ee10869ebfbe/src/main/c/seasocks/util/CrackedUriPageHandler.h)

**Comment by asmyasnikov** [comment]
I see this utils. Is this utils return ALL params (from QUERY_STRING  header of GET-request and body of 
 POST-request)? I need getting params from body of POST request... Not only from QUERY_STRINGheader

**Comment by mattgodbolt** [comment]
There's no support for retrieving query strings from `POST`, I'm afraid: you'll have to handle any `POST`ed data yourself.
