### ISSUE TITLE
Bind to IP

### ISSUE THREAD

**Issue by thecokeguy** [mattgodbolt/seasocks#85]
How do I bind to a specific IP?

**Comment by mattgodbolt** [comment]
Good question, and sorry it wasn't clear how to do this. To pick the interface to listen on, you need to use the `startListening` interface, with code something like:

Instead of:

```cpp
server.serve("/path/to/static_content");
```

Do:

```cpp
server.startListening(ipInHostOrder, port);
server.setStaticPath("/path/to/static_contexnt");
server.loop();
```

Here `ipInHostOrder` is a 32-bit value, the IP address to listen on in host order.

**Comment by thecokeguy** [comment]
Thanks! Btw awesome library ;)

**Comment by mattgodbolt** [comment]
You're so welcome: glad it helped!
