### ISSUE TITLE
seasocks::Server as both REST-server and WebSocket-server on single port runtime?

### ISSUE THREAD

**Issue by asmyasnikov** [mattgodbolt/seasocks#86]
Can I run seasocks::Server as both REST-server and WebSocket-server on single port?
I want to make my server with REST-API and WebSockets API both in runtime.
Sample of my code:
```cpp
seasocks::Server server(logger);
 auto restHandler = std::make_shared<MyRESTHandler>();
 server.addPageHandler(restHandler);
 auto wsHandler = std::make_shared<MyWSHandler>(&server);
 server.addWebSocketHandler("/path?ws", wsHandler);
 if(!server.startListening(my_port)) return EXIT_FAILURE;
 server.loop();
```

But requests like 'http://localhost:my_port/path' and 'ws://localhost:my_port/path?ws' routes into restHandler only. WebSocket-requests cannot routes to wsHandler =(
I don't understand the gist of seasocks kernel. Help me, please!

**Comment by mattgodbolt** [comment]
Yes, absolutely. This is how I ran it at my last company; several RESTful endpoints and one or two websocket endpoints.

The problem with your setup is you're trying to add a handler associated with a query string. The query string is not part of the path of the URL, and Seasocks doesn't support distinguishing websockets from regular REST requests on the query part.

It should work if you remove the `?ws` part from both the `addWebSocketHandler` and the Javascript code you're using. Give it a try and let me know how you get on. Failing that I have some ideas on how to fix up the `MyRESTHandler` part.

Sorry this isn't more clear!

**Comment by asmyasnikov** [comment]
So, if I set different urls for REST-handler and WebSocket-handler (for example, /path and /ws), seasocks can work with both protocols?

**Comment by mattgodbolt** [comment]
That should work, yes.

**Comment by asmyasnikov** [comment]
Unfortunately all requests redirect into path handler, ignore websocket handler =(

**Comment by mattgodbolt** [comment]
Although, it's been a while... perhaps your handler needs to return a `Response::unhandled()` for anything it doesn't recognise...

**Comment by mattgodbolt** [comment]
Yes, it looks like you need to check for Websocket requests in your RESTful endpoint, and ignore:

```
if (request.verb() == Verb::WebSocket) return Response::unhandled();
```

should do the trick (or something similar!)

**Comment by mattgodbolt** [comment]
Hooray! Thanks for your patience, I hadn't remembered that the REST handlers get _every_ request and are expected to indicate when they're not interested.
